apiVersion: batch/v1
kind: Job
metadata:
  name: job-nodeport
spec:
  template:
    spec:
      containers:
      - name: job-nodeport
        image: curlimages/curl:latest
        command: ['sh', '-c', 'curl http://34.82.188.196:30001/']
      restartPolicy: OnFailure
